name: Release

on:
  push:
    branches: [ master, develop, feature/** ]
  pull_request:
    branches: [ master ]
  create:
      tags:
        - v*

jobs:
  build:
    name: Build app
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build: ["windows", "linux", "darwin"]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Make build
        run: make build_${{ matrix.build }}

      - name: Upload release
        uses: actions/upload-artifact@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: release
          path: bin

  release:
    name: Create draft release
    runs-on: ubuntu-latest
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download release
        uses: actions/download-artifact@v2
        with:
          name: release
          path: bin

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            ./bin/*